# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Todo-Main-Swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Todo-Main-Swift
  pod 'GITSTodo', :path=> '../Todo-Modules/GITSTodo' 

end
